### PR TITLE
Playing indicator

### PR DESCRIPTION
**Pull request by nuel-ikwuoma**
## Purpose
* Feature #9 Implementation

## What
* Added visual feedback for currently playing song

## How to Test
* ...

## What to Check
Verify that the following are valid
* Playing a song now displays an icon indicator.

### CODE REVIEW

**Comment by nuel-ikwuoma** [comment]
### A sample demo of what was implemented.
playing_feedback

**Comment by ashinzekene** [comment]
This is really nice work. Thanks Nuel!

**Comment by ashinzekene** [comment]
You can add the `.env` file since it does not contain any secrets, so your build can pass

**Comment by nuel-ikwuoma** [comment]
There's a .env file already in the project root directory, should i overwrite it?

I was thinking linting/formatting issues caused the failing build.

**Comment by ashinzekene** [comment]
Thanks Noah

**Pull request merged**
