### PR TITLE
Added mp3 drag and drop functionality

### PR DESCRIPTION
**Pull request by CliffReimers**
## Purpose
* Allow user to add mp3 files by drag and drop

## What
* Added drag and drop functionality to MainView.jsx

## What to Check
Verify that the following are valid
* It is possible to drag mp3 files from file explorer or desktop to add them to player
* Files that are not in mp3 format will not be added

### CODE REVIEW

**Comment by ashinzekene** [comment]
Thanks, would go through it

**Comment by ashinzekene** [comment]
Fixes #5

**Comment by CliffReimers** [comment]
> I've gone through it.Thanks.
> 
> I saw you tried working on fixing the ESLint errors, I've already created another branch for that. I didn't start the project with ESLint
> 
> Why did you switch from JSON to a JS file for the eslint configuration?

I took the lint fix from this branch: https://github.com/ashinzekene/react-music-player/tree/fix/eslint.
Just wanted to get it running without spending too much time on the lint stuff.

**Comment by ashinzekene** [comment]
Thanks for contributing

**Pull request merged**
